---
all:
  children:
    lab2_switches:
      children:
        cisco_ios:
          hosts:
            DSW1:
              ansible_host: 172.30.30.41

            ASW1:
              ansible_host: 172.30.30.43

            ASW2:
              ansible_host: 172.30.30.44

            SW_DMZ:
              ansible_host: 172.30.30.40
