---

- name: General Config

  hosts: Switches

  tasks:

   - name: Add Banner
      ios_banner:
      banner: login
      text: |
        
 $$$$$$\  $$\      $$\         $$$$$$\   $$$$$$\   $$$$$$\  $$$$$$$$\  $$$$$$\   $$$$$$\  
$$  __$$\ $$ | $\  $$ |       $$  __$$\ $$  __$$\ $$  __$$\ $$  _____|$$  __$$\ $$  __$$\ 
$$ /  \__|$$ |$$$\ $$ |       $$ /  $$ |$$ /  \__|$$ /  \__|$$ |      $$ /  \__|$$ /  $$ |
\$$$$$$\  $$ $$ $$\$$ |       $$$$$$$$ |$$ |      $$ |      $$$$$\    \$$$$$$\  $$ |  $$ |
 \____$$\ $$$$  _$$$$ |       $$  __$$ |$$ |      $$ |      $$  __|    \____$$\ $$ |  $$ |
$$\   $$ |$$$  / \$$$ |       $$ |  $$ |$$ |  $$\ $$ |  $$\ $$ |      $$\   $$ |$$ |  $$ |
\$$$$$$  |$$  /   \$$ |       $$ |  $$ |\$$$$$$  |\$$$$$$  |$$$$$$$$\ \$$$$$$  | $$$$$$  |
 \______/ \__/     \__|$$$$$$\\__|  \__| \______/  \______/ \________| \______/  \______/ 
                       \______| 
        
      state: present

   - name: create a new user
      ios_user:
       name: angie.martinez
       nopassword: True
       sshkey: "cisco"
       state: present
   - name: create a new user
      ios_user:
       name: lorena.rodriguez
       nopassword: True
       sshkey: "cisco"
       state: present
   - name: create a new user
      ios_user:
       name: maritza.virviescas
       nopassword: True
       sshkey: "cisco"
       state: present
      
   - name: configure hostname and domain name
      ios_system:
       hostname: sw_acceso
       domain_name: www.cloudflare.com
       domain_search:
        - ansible.com
        - redhat.com
        - cisco.com
        
    name: configure name servers
      ios_system:
       name_servers:
        - 1.1.1.1
        - 8.8.8.8

   - name: Create vlan
      ios_vlan:
       vlan_id: 200
       name: ANSIBLE
       state: present

   - name: Add interfaces to VLAN
      ios_vlan:
       vlan_id: 200
       interfaces:
        - GigabitEthernet1/0
        - GigabitEthernet1/1

   - name: enable logging to all
      ios_logging:
       dest : on
    
   - name: configure interface
      ios_interface:
       name: GigabitEthernet1/0
       description: to_Users
       speed: 1000
       duplex: half-duplex
       mtu: 512
   - name: configure interface
      ios_interface:
       name: GigabitEthernet1/1
       description: to_Users
       speed: 1000
       duplex: half-duplex
       mtu: 512

   - name: Add loopback
       name: loopback 30
       state: present
