---

- name: General Config

  hosts: Routers

  tasks:

   - name: Add Banner
     ios_banner:
      banner: login
      text: |
       Network Automation with Ansible by @andersonmavi30 on Twitter :D
      state: present
   
   - name: Add loopback
     ios_interface:
       name: Loopback30
       state: present
