---
- name: Lab 5 - Final validation summary
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml

  roles:
    - role: ../roles/lab5_validate
