R1:
  hostname: 172.30.30.41
  platform: cisco_ios
  username: netdevops
  password: cisco
ASW1:
  hostname: 172.30.30.42
  platform: cisco_ios
  username: netdevops
  password: cisco
ASW2:
  hostname: 172.30.30.43
  platform: cisco_ios
  username: netdevops
  password: cisco
ASW3:
  hostname: 172.30.30.44
  platform: cisco_ios
  username: netdevops
  password: cisco
