---
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_command_timeout: 120

ansible_become: true
ansible_become_method: enable

ansible_user: "{{ vault_ios_username }}"
ansible_password: "{{ vault_ios_password }}"
ansible_become_password: "{{ vault_ios_enable_password }}"

lab_name: lab6-eigrp-cicd-pipeline
lab6_management_interface: GigabitEthernet3
