FROM quay.io/ansible/awx-ee:24.6.1

USER root

RUN python3 -m pip install --no-cache-dir \
    ansible-core==2.15.13 \
    ansible-pylibssh==1.4.0 \
    netaddr==1.3.0 \
    netmiko==4.6.0 \
    nornir==3.5.0 \
    nornir-netmiko==1.0.1 \
    pyats==25.9 \
    genie==25.10 \
    pybatfish==2025.7.7.2423 \
    pynetbox==7.8.0 \
    PyYAML==6.0.3

RUN rm -rf \
    /usr/share/ansible/collections/ansible_collections/ansible/netcommon \
    /usr/share/ansible/collections/ansible_collections/ansible/utils \
    /usr/share/ansible/collections/ansible_collections/cisco/ios \
    /usr/share/ansible/collections/ansible_collections/netbox/netbox

RUN ansible-galaxy collection install \
    ansible.netcommon:8.4.0 \
    ansible.utils:6.0.1 \
    cisco.ios:11.3.0 \
    netbox.netbox:3.23.0 \
    -p /usr/share/ansible/collections \
    --force

ENV ANSIBLE_NETWORK_CLI_SSH_TYPE=libssh
ENV ANSIBLE_HOST_KEY_CHECKING=False
ENV PYTHONUNBUFFERED=1

USER 1000
