---
all:
  children:
    lab4:
      children:
        routers:
          hosts:
            R1:
              ansible_host: 172.30.30.42
            R2:
              ansible_host: 172.30.30.43
            R3:
              ansible_host: 172.30.30.44
            R4:
              ansible_host: 172.30.30.45

        switches:
          hosts:
            ASW1:
              ansible_host: 172.30.30.41
